package com.github.rcd47.x2data.lib.unreal.mappings.base;

public enum ETeam {
	
	// note that these values are used as bitmasks in some parts of the native code
	// hence all of the DONT_USE values
	
	eTeam_None,		// = 0
	eTeam_Neutral,	// = 1
	eTeam_One,		// = 2
	eTeam_DONT_USE_3,
	eTeam_Two,		// = 4
	eTeam_DONT_USE_5,
	eTeam_DONT_USE_6,
	eTeam_DONT_USE_7,
	eTeam_XCom,		// = 8
	eTeam_DONT_USE_9,
	eTeam_DONT_USE_10,
	eTeam_DONT_USE_11,
	eTeam_DONT_USE_12,
	eTeam_DONT_USE_13,
	eTeam_DONT_USE_14,
	eTeam_DONT_USE_15,
	eTeam_Alien,		// = 16
	eTeam_DONT_USE_17,
	eTeam_DONT_USE_18,
	eTeam_DONT_USE_19,
	eTeam_DONT_USE_20,
	eTeam_DONT_USE_21,
	eTeam_DONT_USE_22,
	eTeam_DONT_USE_23,
	eTeam_DONT_USE_24,
	eTeam_DONT_USE_25,
	eTeam_DONT_USE_26,
	eTeam_DONT_USE_27,
	eTeam_DONT_USE_28,
	eTeam_DONT_USE_29,
	eTeam_DONT_USE_30,
	eTeam_DONT_USE_31,
	eTeam_TheLost,		// = 32
	eTeam_DONT_USE_33,
	eTeam_DONT_USE_34,
	eTeam_DONT_USE_35,
	eTeam_DONT_USE_36,
	eTeam_DONT_USE_37,
	eTeam_DONT_USE_38,
	eTeam_DONT_USE_39,
	eTeam_DONT_USE_40,
	eTeam_DONT_USE_41,
	eTeam_DONT_USE_42,
	eTeam_DONT_USE_43,
	eTeam_DONT_USE_44,
	eTeam_DONT_USE_45,
	eTeam_DONT_USE_46,
	eTeam_DONT_USE_47,
	eTeam_DONT_USE_48,
	eTeam_DONT_USE_49,
	eTeam_DONT_USE_50,
	eTeam_DONT_USE_51,
	eTeam_DONT_USE_52,
	eTeam_DONT_USE_53,
	eTeam_DONT_USE_54,
	eTeam_DONT_USE_55,
	eTeam_DONT_USE_56,
	eTeam_DONT_USE_57,
	eTeam_DONT_USE_58,
	eTeam_DONT_USE_59,
	eTeam_DONT_USE_60,
	eTeam_DONT_USE_61,
	eTeam_DONT_USE_62,
	eTeam_DONT_USE_63,
	eTeam_Resistance, 		// = 64
	eTeam_DONT_USE_65,
	eTeam_DONT_USE_66,
	eTeam_DONT_USE_67,
	eTeam_DONT_USE_68,
	eTeam_DONT_USE_69,
	eTeam_DONT_USE_70,
	eTeam_DONT_USE_71,
	eTeam_DONT_USE_72,
	eTeam_DONT_USE_73,
	eTeam_DONT_USE_74,
	eTeam_DONT_USE_75,
	eTeam_DONT_USE_76,
	eTeam_DONT_USE_77,
	eTeam_DONT_USE_78,
	eTeam_DONT_USE_79,
	eTeam_DONT_USE_80,
	eTeam_DONT_USE_81,
	eTeam_DONT_USE_82,
	eTeam_DONT_USE_83,
	eTeam_DONT_USE_84,
	eTeam_DONT_USE_85,
	eTeam_DONT_USE_86,
	eTeam_DONT_USE_87,
	eTeam_DONT_USE_88,
	eTeam_DONT_USE_89,
	eTeam_DONT_USE_90,
	eTeam_DONT_USE_91,
	eTeam_DONT_USE_92,
	eTeam_DONT_USE_93,
	eTeam_DONT_USE_94,
	eTeam_DONT_USE_95,
	eTeam_DONT_USE_96,
	eTeam_DONT_USE_97,
	eTeam_DONT_USE_98,
	eTeam_DONT_USE_99,
	eTeam_DONT_USE_100,
	eTeam_DONT_USE_101,
	eTeam_DONT_USE_102,
	eTeam_DONT_USE_103,
	eTeam_DONT_USE_104,
	eTeam_DONT_USE_105,
	eTeam_DONT_USE_106,
	eTeam_DONT_USE_107,
	eTeam_DONT_USE_108,
	eTeam_DONT_USE_109,
	eTeam_DONT_USE_110,
	eTeam_DONT_USE_111,
	eTeam_DONT_USE_112,
	eTeam_DONT_USE_113,
	eTeam_DONT_USE_114,
	eTeam_DONT_USE_115,
	eTeam_DONT_USE_116,
	eTeam_DONT_USE_117,
	eTeam_DONT_USE_118,
	eTeam_DONT_USE_119,
	eTeam_DONT_USE_120,
	eTeam_DONT_USE_121,
	eTeam_DONT_USE_122,
	eTeam_DONT_USE_123,
	eTeam_DONT_USE_124,
	eTeam_DONT_USE_125,
	eTeam_DONT_USE_126,
	eTeam_All,  // = 127
	
}
